// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: protobuf/events.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Exp int32 `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *UserEvent) Reset() {
	*x = UserEvent{}
	mi := &file_protobuf_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEvent) ProtoMessage() {}

func (x *UserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEvent.ProtoReflect.Descriptor instead.
func (*UserEvent) Descriptor() ([]byte, []int) {
	return file_protobuf_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserEvent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserEvent) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

type UserUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Exp int32 `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *UserUpdate) Reset() {
	*x = UserUpdate{}
	mi := &file_protobuf_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdate) ProtoMessage() {}

func (x *UserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdate.ProtoReflect.Descriptor instead.
func (*UserUpdate) Descriptor() ([]byte, []int) {
	return file_protobuf_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserUpdate) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserUpdate) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

var File_protobuf_events_proto protoreflect.FileDescriptor

var file_protobuf_events_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x49, 0x64, 0x6c, 0x65, 0x45, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x22, 0x2d, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65,
	0x78, 0x70, 0x22, 0x2e, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65,
	0x78, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_events_proto_rawDescOnce sync.Once
	file_protobuf_events_proto_rawDescData = file_protobuf_events_proto_rawDesc
)

func file_protobuf_events_proto_rawDescGZIP() []byte {
	file_protobuf_events_proto_rawDescOnce.Do(func() {
		file_protobuf_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_events_proto_rawDescData)
	})
	return file_protobuf_events_proto_rawDescData
}

var file_protobuf_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_events_proto_goTypes = []any{
	(*UserEvent)(nil),  // 0: IdleEngine.UserEvent
	(*UserUpdate)(nil), // 1: IdleEngine.UserUpdate
}
var file_protobuf_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_events_proto_init() }
func file_protobuf_events_proto_init() {
	if File_protobuf_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_events_proto_goTypes,
		DependencyIndexes: file_protobuf_events_proto_depIdxs,
		MessageInfos:      file_protobuf_events_proto_msgTypes,
	}.Build()
	File_protobuf_events_proto = out.File
	file_protobuf_events_proto_rawDesc = nil
	file_protobuf_events_proto_goTypes = nil
	file_protobuf_events_proto_depIdxs = nil
}
